media:
  input: static/images
  output: images
content:
  - name: pages
    label: Pages
    path: content
    type: collection
    view:
      fields: [ title, subtitle, menu.main.name ]
    fields:
      - name: title
        label: Title
        type: string
      - name: subtitle
        label: "Sub-title"
        type: string
      - name: menu.main.name
        label: "Menu Name"
        type: string
      - name: body
        label: Body
        type: rich-text
        options:
          image:
            path: static/images
            extensions: [ jpg, jpeg, png ]
  - name: blog
    label: Posts
    path: content/posts
    type: collection
    fields:
      - name: title
        label: Title
        type: string
      - name: subtitle
        label: Subtitle
        type: string
      - name: date
        label: Date
        type: datetime
      - name: excerpt
        label: Excerpt
        type: string
      - name: show_in_home_posts
        label: Show in Home Posts
        type: boolean
      - name: show_in_sidebar
        label: Show in Sidebar
        type: boolean
      - name: content_img
        label: Content Image
        type: object
        fields:
          - name: alt
            label: Alt Text
            type: string
          - name: enabled
            label: Enabled
            type: boolean
          - name: path
            label: Image Path
            type: string
      - name: body
        label: Body
        type: rich-text
        options:
          image:
            path: static/images
            extensions: [ jpg, jpeg, png ]
