media: 
  input: static/images
  output: /images
content:
  - name: pages
    label: Pages
    path: content
    type: collection
    exclude: [ _index.md ]
    view:
      fields: [ title, subtitle ]
    fields:
      - name: title
        label: Title
        type: string
      - name: subtitle
        label: "Sub-title"
        type: string
      - name: menu
        label: "Menu"
        hidden: true
        type: object
        fields:
          - name: main
            label: Main
            type: object
            fields:
            - name: name
              label: Name
              type: string
            - name: weight
              label: Weight
              type: number
          - name: footer
            label: Footer
            type: object
            fields:
            - name: name
              label: Name
              type: string
            - name: weight
              label: Weight
              type: number
      - name: body
        label: Body
        type: rich-text
        options:
          image:
            path: images
            extensions: [ jpg, jpeg, png ]
      - name: content_img
        label: "Content Image"
        hidden: true
        type: object
        fields:
          - name: enabled
            label: Enabled
            type: boolean
          - name: path
            label: "Image Path"
            type: string
          - name: url
            label: "Image URL"
            type: string
      - name: sidebar
        label: Sidebar
        hidden: true
        type: object
        fields:
          - name: enabled
            label: Enabled
            type: boolean
          - name: side
            label: Side
            type: string
            options:
              - left
              - right
  - name: blog
    label: Posts
    path: content/posts
    type: collection
    fields:
      - name: title
        label: Title
        type: string
      - name: subtitle
        label: Subtitle
        type: string
      - name: date
        label: Date
        type: date
      - name: excerpt
        label: Excerpt
        type: string
      - name: show_in_home_posts
        label: "Show in Home Posts"
        hidden: true
        type: boolean
      - name: show_in_sidebar
        label: "Show in Sidebar"
        hidden: true
        type: boolean
      - name: alt_img
        label: Alternative Image
        hidden: true
        type: string
      - name: content_img
        label: "Content Image"
        hidden: true
        type: object
        fields:
          - name: alt
            label: Alt Text
            type: string
          - name: enabled
            label: Enabled
            type: boolean
          - name: path
            label: Image Path
            type: string
      - name: body
        label: Body
        type: rich-text
        options:
          image:
            path: static/images
            extensions: [ jpg, jpeg, png ]
