media:
  input: static/images
  output: /category/images
content:
  - name: pages
    label: Pages
    path: content
    type: collection
    view:
      fields: [ title, subtile, name ]
    fields:
      - name: title
        label: Title
        type: string
      - name: title
        label: Title
        type: string
      - name: name
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
  - name: blog
    label: Posts
    path: content/posts
    type: collection