---
title: NWA Community Cat Project
baseURL: "/"
params:
  landing_template: home
  palette: green
  palettes:
    blue:
      sass:
        gradient1: "#27a1e3"
        gradient2: "#e7232a"
        accent1: "#5f9dd2"
        accent2: "#758ce1"
        accent3: "#e286a9"
    green:
      sass:
        gradient1: "#16f4cf"
        gradient2: "#6532e5"
        accent1: "#54d3cf"
        accent2: "#4f92d1"
        accent3: "#8075e5"
menu:
  main:
  - url: "/left-sidebar"
    name: Left Sidebar
    parent: layouts
    weight: 3
    identifier: normal1
  - url: "#"
    name: Option Four
    parent: submenu
    weight: 10
    identifier: normal7
  - url: "#"
    name: Option Three
    parent: submenu
    weight: 8
    identifier: normal6
  - url: "#"
    name: Option Two
    parent: submenu
    weight: 4
    identifier: normal5
  - url: "#"
    name: Option One
    parent: submenu
    weight: 2
    identifier: normal4
  - url: "#"
    name: Submenu
    parent: layouts
    weight: 11
    identifier: submenu
  - url: "/no-sidebar"
    name: No Sidebar
    parent: layouts
    weight: 9
    identifier: normal3
  - url: "/right-sidebar"
    name: Right Sidebar
    parent: layouts
    weight: 5
    identifier: normal2
  - url: "#"
    name: Page Layouts
    weight: 6
    identifier: layouts
  footer:
  - url: https://www.stackbit.com
    name: Made with Stackbit
    weight: 4
    identifier: normal8
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
